//go:build linux && amd64

package assets

import _ "embed"

// LuaSocketCoreLinuxAMD64 is socket.core for BizHawk (Lua 5.4 / luasocket 3.1).
// Generated by scripts/build-luasocket-linux-amd64.sh — not version controlled.
//
//go:embed luasocket/linux-amd64/core.so
var LuaSocketCoreLinuxAMD64 []byte
