name: Release Go Server

on:
  push:
    tags:
      - "v*" # runs only when you push a tag like v1.0.0

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    env:
      DIST_DIR: dist/server

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build binaries
        run: |
          set -e
          mkdir -p $DIST_DIR
          
          # Build server binaries for different platforms
          GOOS=windows GOARCH=amd64 go build -o $DIST_DIR/bizshuffle-server.exe ./cmd/server
          GOOS=linux   GOARCH=amd64 go build -o $DIST_DIR/bizshuffle-server ./cmd/server
          
          # Copy web UI files
          mkdir -p $DIST_DIR/web
          if [ -d web ]; then
            cp -r web/* $DIST_DIR/web/
          fi
          
          # Copy plugins
          mkdir -p $DIST_DIR/plugins
          if [ -d plugins ]; then
            cp -r plugins/* $DIST_DIR/plugins/
          fi
          
          # Create release archives
          cd $DIST_DIR
          zip -r bizshuffle-server-windows-amd64.zip bizshuffle-server.exe web plugins
          zip -r bizshuffle-server-linux-amd64.zip bizshuffle-server web plugins
          cd ..

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.DIST_DIR }}/bizshuffle-server-windows-amd64.zip
            ${{ env.DIST_DIR }}/bizshuffle-server-linux-amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
