name: Release Go Server

on:
  push:
    tags:
      - "v*" # runs only when you push a tag like v1.0.0

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build binaries
        run: |
          set -e
          mkdir -p dist
          
          # Build server binaries for different platforms
          GOOS=windows GOARCH=amd64 go build -o dist/bizshuffle-server.exe ./cmd/server
          GOOS=linux   GOARCH=amd64 go build -o dist/bizshuffle-server ./cmd/server
          
          # Copy web UI files
          mkdir -p dist/web
          if [ -d web ]; then
            cp -r web/* dist/web/
          fi
          
          # Copy plugins
          mkdir -p dist/plugins
          if [ -d plugins ]; then
            cp -r plugins/* dist/plugins/
          fi
          
          # Create release archives
          cd dist
          zip -r bizshuffle-server-windows-amd64.zip bizshuffle-server.exe web plugins
          zip -r bizshuffle-server-linux-amd64.zip bizshuffle-server web plugins
          cd ..

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/bizshuffle-server-windows-amd64.zip
            dist/bizshuffle-server-linux-amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
